import { Head } from 'next/document';
import Header from '../components/atoms/Header';
import HeroSection from '@/components/molecules/HeroSection';
import CardsSection from '@/components/molecules/CardsSection';
import OffersSection from '@/components/molecules/OffersSection';
import Footer from '@/components/atoms/Footer';
import React, { useState } from 'react';
import Login from '@/components/molecules/Login';
import 'react-modern-drawer/dist/index.css';
import SignUpDrawer from '@/components/molecules/SignUpDrawer';

export default function Home() {
  const [isModalOpen, setModalOpen] = useState<boolean>(false);
  const [isDrawerOpen, setDrawerOpen] = useState<boolean>(false);

  function closeModal(): void {
    setModalOpen(false);
  }

  function openModal(): void {
    setModalOpen(true);
  }

  function handleSignUpClick(): void {
    setDrawerOpen(true);
  }

  function closeDrawer(): void {
    setDrawerOpen(false);
  }

  return (
    <div>
      {/* <Head>
        <title>Comwell Hotels</title>
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <meta name='description' content='Generated by bla bla bla' />
        <link rel='icon' href='/favicon.ico' />
      </Head> */}
      <div>
        <Header
          handleLocationClick={() => console.log('TODO')}
          handleProfileClick={openModal}
          handleMenuClick={() => console.log('TODO')}
        >
          <Login isOpen={isModalOpen} closeModal={closeModal} onSignUpClick={handleSignUpClick} />
        </Header>
        <main>
          <HeroSection />
          <CardsSection />
          <OffersSection />
          <SignUpDrawer isOpen={isDrawerOpen} onClose={closeDrawer} />
        </main>
        <Footer />
      </div>
    </div>
  );
}
